### ISSUE TITLE
Error instaling SPADE under windows

### ISSUE THREAD

**Issue by jtomasrl** [javipalanca/spade#10]
Im getting an error when installing SPADE under windows 7/8

![error](https://f.cloud.github.com/assets/542860/1778100/872fe0c8-682f-11e3-9973-cb5148a4501f.jpg)

**Comment by etmschneider** [comment]
Hello,
I got the problem today since I wanted to install Spade on my Windows 10 computer. I downloaded Python2.7 (current), and also the SPADE archive just in case.
Then I tried the python setup.py install from the SPADE directory. It failed with the issue about the win32prng.c.
Then I switched to use pip install SPADE... Same problem. Though I expected all the files to be there.
Ah yes, I have VS 2015 and VS2017, though I am not sure I have the VS Tools for Python or equivalents for VS2017.
So I copied and pasted the source for the C file in a file, named it win32.prng.c then I put it in every folder / subfolder of c:\spade\build\lib.win32-2.7\tslite and c:\spade\build\temp.win32-2.7 and it worked.

Now I have to see the log (or kind of) to see exactly what happened.

I hope it might help as I don't think I will be alone to have that issue.

--- 
  Etienne
