### ISSUE TITLE
My agent doesn't start

### ISSUE THREAD

**Issue by febefeebs** [javipalanca/spade#36]
I just wrote my first agent program from the example that you give in the instructions, but when I run it, it just appears "Starting agent. . . " and it doesn't show the rest "Agent: agent@myhost.myprovider.com registered correctly (inform)".
I suposse it's something about the start method.
I'm using myhost as 127.0.0.1.
Could you please help me?
Thanks!

**Comment by javipalanca** [comment]
are you using agent@127.0.0.1 as name? Note that myhost.myprovider.com is a fake address for example purposes.

**Comment by febefeebs** [comment]
Yes, thank you! I already fixed that problem, but now I have another...
I have an agent that is supposed to receive messages, from the example that you give in chapter 4, "Agent Communication: Sending and receiving messages". but it is not working. 
I start SPADE as usual, and then run the program with the receiver agent, without sending anything and it prints in no less than 10 seconds that it received a message... And I don't know what is happening. 
This is what it prints as a message:
I got a message!
<fipa-message act="inform"><sender><agent-identifier><name id="ams.127.0.0.1"/><addresses><url href="xmpp://ams.127.0.0.1"/></addresses></agent-identifier></sender><content><presence xmlns="jabber:client" to="agent@127.0.0.1" type="subscribed" id="1" from="ams.127.0.0.1" /></content><ontology>Presence</ontology><protocol>subscribed</protocol><conversation-id>327bb658b6044be0bfb9f5214a546b9c</conversation-id></fipa-message>

Could you please help me on this?!!
Thanks!

**Comment by javipalanca** [comment]
That's because your behavior is registered as a default behavior (see `self.setDefaultBehaviour(rb)`). A default behavior receives every message that was unexpected and which has no other behavior waiting for it. That is why you see more messages in that behavior, because SPADE is continuously sending and receiving messages regarding the XMPP protocol and the FIPA protocol. If you want a behavior that only receives one kind of message use `self.addBehaviour(rb, template)` instead of setDefaultBehaviour. Note that in that case you MUST use a message template to filter which kind of messages are received by that behavior.

However, I know that the documentation is a little bit confusing, but it is being improved in the 3.0 release that I hope will be ready this year. You can get a sneak preview at http://spade-mas.readthedocs.io/en/feature-3.0/
