### ISSUE TITLE
Some questions about performance

### ISSUE THREAD

**Issue by GGurtner** [javipalanca/spade#43]
* SPADE version: 3.0.3
* Python version: 3.6
* Operating System: linux mint 18

Hi guys, first let me congratulate you for this library, it is really impressive. 

In short, I have a question about performance, but it is probably more an issue with the server than with SPADE itself. I am wondering if you could give me some advice nevertheless.

We are considering using SPADE for a new agent-based model that we are currently planning for air transportation. We are very interested in using SPADE, but after some initial tests, it seems that sending and receiving messages would have a high impact on the computational performance of the model.

To give you some context, we are trying to use SPADE with around 100k agents. A very quick estimation tells us that more than 3 millions messages will be sent during a single simulation. During our tests, using a local prosody server, we estimated that the time to send and receive a message was around 0.02 second, which puts around the total CPU time to 60k seconds, more than 16 hours, just for the messages. This is too much for us, unfortunately.

So my questions are the following I guess:
* Does the 0.02 second seem normal to you for the transfer time?
* Is there any way to decrease this transfer time?
* Is it mainly due to the server?
* Shall we try others?
* Do you have any advice for the server configuration?

Thanks for taking the time to read this, and keep up the good work!

**Comment by javipalanca** [comment]
Hi,
We haven't still made any test about performance. But of course, since 3M messages are a lot of messages, a server-based architecture like XMPP may be hard to optimize.

However, one of the next plugins I would like to have is a kind of p2p message sending for these use cases. My idea is to use ZeroMQ or any other distributed messaging framework to send p2p messages when the scenario requires it, but without losing the advantages of XMPP.

I would like to receive as many advices as possible about this :)
