### ISSUE TITLE
Concurrency issues with 10+ agents

### ISSUE THREAD

**Issue by L-Piao** [javipalanca/spade#54]
* SPADE version: 3.0.9
* Python version: 3.6.5
* Operating System: Win10 x64

### Description

For a simulation containing 100+ agents, I've been testing SPADE and xmpp servers. Currently I'm using the xmpp server "jwchat.org", chose a jid, then created multiple resources with the same jid (i think the theoretical maximum is 256 resources). It simply didn't work.

### What I Did

Even when I use dummy agents (without behavior), i can't even create more than 10 or 11 of such agents. Once the number of agents exceed 10, i'll receive an error of "cancellation due to concurrency", as shown below:

```
LOAD1:	Agent is online!
LOAD2:	Agent is online!
LOAD3:	Agent is online!
LOAD4:	Agent is online!
LOAD5:	Agent is online!
LOAD6:	Agent is online!
LOAD7:	Agent is online!
LOAD8:	Agent is online!
LOAD9:	Agent is online!
LOAD10:	Agent is online!
broker task failed
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\aioxmpp\stream.py", line 1939, in _run
    timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\asyncio\tasks.py", line 313, in wait
    return (yield from _wait(fs, timeout, return_when, loop))
  File "C:\ProgramData\Anaconda3\lib\asyncio\tasks.py", line 396, in _wait
    yield from waiter
**concurrent.futures._base.CancelledError**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\aioxmpp\stream.py", line 892, in _done_handler
    task.result()
  File "C:\ProgramData\Anaconda3\lib\site-packages\aioxmpp\stream.py", line 1987, in _run
    raise self._xmlstream_exception
aioxmpp.errors.StreamError: stream error: {urn:ietf:params:xml:ns:xmpp-streams}conflict ('Replaced by new connection')
stream failed: stream error: {urn:ietf:params:xml:ns:xmpp-streams}conflict ('Replaced by new connection')
main failed
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\aioxmpp\stream.py", line 1939, in _run
    timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\asyncio\tasks.py", line 313, in wait
    return (yield from _wait(fs, timeout, return_when, loop))
  File "C:\ProgramData\Anaconda3\lib\asyncio\tasks.py", line 396, in _wait
    yield from waiter
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\aioxmpp\node.py", line 824, in _on_main_done
    task.result()
  File "C:\ProgramData\Anaconda3\lib\site-packages\aioxmpp\node.py", line 989, in _main
    yield from self._main_impl()
  File "C:\ProgramData\Anaconda3\lib\site-packages\aioxmpp\node.py", line 965, in _main_impl
    raise exc
  File "C:\ProgramData\Anaconda3\lib\site-packages\aioxmpp\stream.py", line 892, in _done_handler
    task.result()
  File "C:\ProgramData\Anaconda3\lib\site-packages\aioxmpp\stream.py", line 1987, in _run
    raise self._xmlstream_exception
aioxmpp.errors.StreamError: stream error: {urn:ietf:params:xml:ns:xmpp-streams}conflict ('Replaced by new connection')
LOAD11:	Agent is online!
broker task failed
Traceback (most recent call last):
(...and so on...)
```
Regarding this I have several questions:

**[A Survey] Which xmpp server do you use personally?**
What're the good features and how did you find them out?

1. Has anyone tested SPADE with large numbers of (100+) agents? Which xmpp server would you recommend for such an application? Is it possible to create even more than 256 agents on SPADE? How if yes, or why don't you recommend doing it?

2. @javipalanca once mentioned that it's possible to create one's own xmpp-server (I hope this would resolve the concurrency issues).  Is there a handy tutorial (step-by-step) on how to do it? Thanks!

3. async/await issues
In SPADE, is there a practical way to avoid "concurrent.futures._base.CancelledError"? Personally i'm not familiar with multi-threading, but I would be very grateful if you could give me (us all) some tricks to avoid it (e.g., by adding await asyncio.sleep()).
_For example, i'd like to initialize one agent that further creates a list of other agents. However, I can't add an async-sleep between the creation of two agents._ 

4. When printing, how to avoid concurrent prints from different agents like this (where each agent should print on separate lines): 

    LOAD55:	Agent is online!
    LOAD55:	Agent starts the trade behaviour.
    LMO:	Starts the clearLocalMarket behaviour: in 3 steps
    LMO:	Step 1: LMO sends call-for-bids to prosumers.
    ch03218_Avg_kW:	Received a call-for-bid from LMO.
    ch03231_Avg_kW:	Received a call-for-bid from LMO.LOAD55:	Received a call-for-bid from LMO.
    ch03205_Avg_kW:	Received a call-for-bid from LMO.

    ch03244_Avg_kW:	Received a call-for-bid from LMO.LOAD40:	Received a call-for-bid from LMO.
    LOAD1:	Received a call-for-bid from LMO.
    LOAD20:	Received a call-for-bid from LMO.

5. In SPADE, are there any functions for an agent to search for other agents of a certain class, name, or feature? Some agent platforms like JADE provide such convenient functions, and I've been looking for a replacement of that in SPADE.

Finally, thank you all so much for making SPADE as fancy as it is!

Cheers,
Piao

**Comment by javipalanca** [comment]
It's a common mistake to reuse a jid  for all your agents. The jid is the unique identifier of an agent and also its address. Although XMPP accepts multiple connections to different resources, neither aioxmpp nor SPADE are designed that way.

I recommend you to use a unique JID for every agent, otherwise, who is going to receive a message?

> **[A Survey] Which xmpp server do you use personally?**
> What're the good features and how did you find them out?

I use prosody, as is stated in the SPADE docs. It's the most used server nowadays, even by the XMPP Foundation, and it works really well.
On the other hand it is made with Lua and I would like to have my own python asyncio XMPP server to make it easier to be integrated with SPADE.

> 1. Has anyone tested SPADE with large numbers of (100+) agents? Which xmpp server would you recommend for such an application? Is it possible to create even more than 256 agents on SPADE? How if yes, or why don't you recommend doing it?

Yes I have. Just use different JIDs for your agents. 
Also, I have just published some minutes ago a new SPADE version (3.1) which introduces a new mechanism that speeds up a lot communications when agents are sharing the same script (a.k.a the same process). It's a transparent mechanism, you don't have to do anything, and messages are just delivered inside the process without being routed through the external server.

> 2. @javipalanca once mentioned that it's possible to create one's own xmpp-server (I hope this would resolve the concurrency issues).  Is there a handy tutorial (step-by-step) on how to do it? Thanks!

That's a big question. My thoughts is that using asyncio would be a great base to create a quick server. But the architecture of such server needs to be designed with care.

> 3. async/await issues
>    In SPADE, is there a practical way to avoid "concurrent.futures._base.CancelledError"? Personally i'm not familiar with multi-threading, but I would be very grateful if you could give me (us all) some tricks to avoid it (e.g., by adding await asyncio.sleep()).

The trick is: don't forget to await coroutines (those that are defined with an async statement before the def). It seems to me that in modern versions of Python it warns you that you haven't awaited a coroutine.

>    _For example, i'd like to initialize one agent that further creates a list of other agents. However, I can't add an async-sleep between the creation of two agents._

The 3.1 release provides you some tricks to do that in an easier way. Now, when you start an agent from inside a coroutine, the start method is also a coroutine, so it has to be awaited. Otherwise, when you call that same method outside a coroutine it behaves as a sync method and it mustn't be awaited.
Also, in this last case, when the method does not behave as a coroutine, it returns a future, so you can make future.result() to block the execution until the start method has finished.

This works the same for the stop method and a new method of Behavior called join. (Only in 3.1!)

> 4. When printing, how to avoid concurrent prints from different agents like this (where each agent should print on separate lines):

When events happen in an async environment you don't have fine control about when things are executed. They just happen "at the same time" (this is not strictly correct, but it's enough for the explanation).

> 5. In SPADE, are there any functions for an agent to search for other agents of a certain class, name, or feature? Some agent platforms like JADE provide such convenient functions, and I've been looking for a replacement of that in SPADE.

Currently there is no AMS or DF in SPADE, which are the agents that allow to search for other agents or services in JADE (FIPA, really). This is due to SPADE's platform-less approach, which tries to have a very small and fast core. However, the possibility of creating plugins for SPADE is explained in the documentation, so, if you think this is an interesting feature: just write a plugin! :)

> Finally, thank you all so much for making SPADE as fancy as it is!

Thanks for using SPADE and for the feedback.

**Comment by hdonancio** [comment]
@javipalanca is in the scope of the project spade 3 adhere to FIPA standards?

**Comment by javipalanca** [comment]
@hdonancio SPADE 3 is not planned to be FIPA compatible, as it seems that the FIPA Foundation is not currently in operation. In addition, I consider that the XMPP approach is much more interesting for standard intercommunication between entities (both human and agents). 

Anyway, as SPADE's intention is to be extensible, it wouldn't be complicated if someone were to write a plugin that would give for example FIPA HTTP support to SPADE agents. But it should be a plugin, not a part of the SPADE core.

There are probably XMPP extensions or components that could be used as alternatives to AMS and DF, but at the moment I haven't explored them.
